@extends('admin.layouts.master')
@section('style')
@endsection
@section('content')
    @include('admin.layouts.error-message')
    @include('admin.layouts.flash-message')
@endsection
@section('script')
@stop